#!/usr/bin/env zsh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_shadow                off
yabai -m config external_bar                 all:40:0


yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            stack

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  4
yabai -m config bottom_padding               4
yabai -m config left_padding                 4
yabai -m config right_padding                4
yabai -m config window_gap                   4

# apps to not manage (ignore)
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^FaceTime" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Messages" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Cisco AnyConnect Secure Mobility Client" manage=off

# borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 &
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"


echo "yabai configuration loaded.."
